### ISSUE TITLE
json parsing

### ISSUE THREAD

**Issue by xivanc** [fabiocicerchia/nginx-lua#140]
**Is your feature request related to a problem? Please describe.**
I have not been able to find out which of the existing lua modules in this repo can be used for json parsing.

**Describe the solution you'd like**
If the json parsing feature is not supported by any of the existing modules, ideally if some standard and battle-tested module would be included, like https://github.com/rxi/json.lua or https://github.com/mpx/lua-cjson or sth similar.

**Comment by fabiocicerchia** [comment]
Hi @xivanc, could you try with [this lua-cjson](https://luarocks.org/modules/openresty/lua-cjson) module (installable via luarocks)? Would it work for you?

**Comment by xivanc** [comment]
@fabiocicerchia Thanks for the answer. Yes, installing it explicitly into an already running docker image with the command `luarocks install lua-cjson` works. I just wanted to avoid explicitly running this command after the docker is initialised. If I want to have it out of the box, perhaps the best way for me would be to update docker entrypoint and build my custom version of the image from this repo?
