### ISSUE TITLE
cannot run the docker

### ISSUE THREAD

**Issue by ariefMudahMy** [fabiocicerchia/nginx-lua#2]
Hi, 
i get error when try to just run the image container

$ docker run --rm -p 80:8080 -p 443:8433 docker.io/fabiocicerchia/nginx-lua:1.19.0
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/lib/libluajit-5.1.so.2)
Error relocating /usr/local/lib/libluajit-5.1.so.2: _Unwind_GetCFA: symbol not found
Error relocating /usr/local/lib/libluajit-5.1.so.2: _Unwind_SetGR: symbol not found
Error relocating /usr/local/lib/libluajit-5.1.so.2: _Unwind_SetIP: symbol not found
Error relocating /usr/local/lib/libluajit-5.1.so.2: _Unwind_RaiseException: symbol not found
Error relocating /usr/local/lib/libluajit-5.1.so.2: _Unwind_DeleteException: symbol not found
/docker-entrypoint.sh: Configuration complete; ready for start up

anything i need to configure?

**Comment by fabiocicerchia** [comment]
Hi,
thank you for reporting the bug.

I've just pushed the fix, you could update you local image by doing a `docker pull fabiocicerchia/nginx-lua`.
You could start the container by running:
```shell
docker run --rm -p 8080:80 -p 8443:443 docker.io/fabiocicerchia/nginx-lua:1.19.0
```

The ports exposed by the Dockerfile are `80` and `443`. `8080` and `8443` will be mapped on your host. So by opening http://localhost:8080 you should see the message `Welcome to nginx!`.

If you have any problems please let me know ;)

**Comment by ariefMudahMy** [comment]
thx for the fixing it
