### ISSUE TITLE
openssl module

### ISSUE THREAD

**Issue by namedgraph** [fabiocicerchia/nginx-lua#21]
**Is your feature request related to a problem? Please describe.**
The openssl module is not installed: https://github.com/zhaozg/lua-openssl

**Describe the solution you'd like**
How do I install it? Or does the image need changes? Like Lua being recompiled?

**Describe alternatives you've considered**
Switching to a different nginx+Lua image or building my own.

**Additional context**
I'm trying to invoke openssl functions in nginx.conf:
https://stackoverflow.com/a/56370180/1003113

**Comment by fabiocicerchia** [comment]
Thank you for reporting the issue.

I've just closed the issue #18, now there's support for luarocks.
The openssl module could be install, as per documentation, with `luarocks install openssl`.

@namedgraph If it is ok for you I can close this issue.

**Comment by namedgraph** [comment]
Yes you can close it.

Is the new image (with luarocks) out already?

**Comment by fabiocicerchia** [comment]
There's an unexpected error on Fedora's repo which is preventing the pipeline to complete correctly.

<img width="628" alt="Screenshot 2021-02-03 at 22 07 45" src="https://user-images.githubusercontent.com/11521/106809687-42506c00-666c-11eb-8c10-9f3594880a6b.png">

Once resolved I'll push the new images for each distro flavour.
In the meantime, I'm building the Alpine version locally and release it soon, so it'll bypass the issue.
