### ISSUE TITLE
Nginx does not respond

### ISSUE THREAD

**Issue by ankitnayan** [fabiocicerchia/nginx-lua#22]
I am using image `fabiocicerchia/nginx-lua:1.19.0-ubuntu18.04` and using curl to send requests. The curl seems to keep waiting for a response from NGINX. The Nginx does not log requests. it seems nginx does not listen them. I tried at port 443.

**Comment by fabiocicerchia** [comment]
@ankitnayan thank you for reporting the issue, I'm going to check this issue asap.
In the meantime could you please share the nginx configuration, also could be helpful to have the exact curl command used for your test.
Thank you

**Comment by ankitnayan** [comment]
@fabiocicerchia it was an issue at my end. I was adding conf at `/etc/nginx/conf.d/ `which is not automatically picked up. 
I now have added the conf at `/etc/nginx/nginx.conf` and it works now
