### ISSUE TITLE
Errror: module 'resty.dns.resolver' not found:

### ISSUE THREAD

**Issue by ankitnayan** [fabiocicerchia/nginx-lua#23]
I am using `local resolver = require "resty.dns.resolver"` code and it shows 
```
Errror: module 'resty.dns.resolver' not found:
```
I suppose this module is automatically loaded, right?
Also, from the example at [lua-resty-dns](https://github.com/fabiocicerchia/nginx-lua/blob/1b50d748199a1231a725c6680ec63c561adfd6d9/docs/examples/lua-resty-dns.md) what should the value of
`lua_package_path "/path/to/lua-resty-dns/lib/?.lua;;";` be? 

I am using the below nginx config to dynamically route grpc requests
```
upstream grpcservers {
    server 127.0.0.1; 
    balancer_by_lua_block {
        local balancer = require "ngx.balancer"

        local ok, err = balancer.set_current_peer(ngx.ctx.address, "4317")
        if not ok then
            ngx.log(ngx.ERR, "failed to set the current peer: ", err)
            return ngx.exit(500)
        end
    }

    keepalive 10;
}

server {
    server_name  <server_name>;
    listen       80;
    listen 443 http2;
    location /opentelemetry.proto.collector.trace.v1.TraceService/Export {

              auth_request /apiTokenAuth;

              error_page 401 = @error401;
              error_page 400 = @error400;

              access_by_lua_block {
                  local defaults = ngx.shared.defaults
                  local resolver = require "resty.dns.resolver"

                  local namespace = ngx.var.upstream_http_namespace
                  local service = "myservice.${namespace}.cluster.local";

                  local r, err = resolver:new{ nameservers = { "kube-dns.kube-system.svc.cluster.local" } }
                  local answers, err = r:query(service, nil, {})
                  if answers.errcode then
                      ngx.say("server returned error code: ", answers.errcode,
                              ": ", answers.errstr)
                  end

                  for i, ans in ipairs(answers) do
                      ngx.ctx.address = ans.address
                      break
                  end
              }
              grpc_pass grpc://grpcservers;
    }
    location /apiTokenAuth {
        internal;
        # proxy_set_header Host $host;
        add_header Access-Control-Allow-Origin "*";
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_pass http://token-verifier:8080/validateApiToken;
    }

    location @error401 {
        return 401 'unauthorised';
    }    
    location @error400 {
        return 400 'bad request';
    } 
}

              
```

**Comment by ankitnayan** [comment]
Also is the value of nameserver correct if I am using Kubernetes? I used to use below resolver when deploying nginx in k8s.
```
              resolver kube-dns.kube-system valid=10s;
              proxy_set_header   Host $host;
              proxy_pass http://signoz-query-service.$namespace.svc.cluster.local:8080/api/$1$is_args$args;
```
We don't have an option to use a variable in grpc_pass, so trying Lua to make it work

**Comment by fabiocicerchia** [comment]
@ankitnayan I believe you're using the version `fabiocicerchia/nginx-lua:1.19.0-ubuntu18.04` as per #22, could you please switch to `fabiocicerchia/nginx-lua:1.19.7-ubuntu20.04` since the support is only for the latest nginx version?
Sorry, but the early versions of nginx-lua weren't perfect and have some bugs in them :(
Do you need explicitly to support 1.19.0 on ubuntu 18.04?

**Comment by ankitnayan** [comment]
@fabiocicerchia On updating to `fabiocicerchia/nginx-lua:1.19.7-ubuntu20.04` the error is gone. Now the request is failing silently without writing to Nginx logs. 
- Can you point me towards enabling logs in Lua?
- Is the nameserver correct in the above configuration for Kubernetes?

**Comment by vikas-tawniya** [comment]
> @vikas-tawniya which version are you using at the moment? Are you facing the same error?

I am using the lates docker container. I am not familiar with lua, so I tried importing ```require``` directly with resty.dns.client and it couldn't find the library, even though I have installed it with luarocks when building my image.

Also I had to install outils-md5 as luarocks required it to download and install stuff
