### ISSUE TITLE
module 'cjson' not found

### ISSUE THREAD

**Issue by kalyan312** [fabiocicerchia/nginx-lua#34]
I used the docker image, But it when I added `cjson` the following error  showing  **module 'cjson' not found**

**Comment by fabiocicerchia** [comment]
Hi @kalyan312, could you please provide me with some more details about the issue?
Some code snippets or steps to replicate the issue would be very helpful to me in order to fix it as soon as possible.
Thank you.

**Comment by clintmiller** [comment]
Hi, @fabiocicerchia- I'm running into this, too. Just a simple
```
local json = require 'cjson'
```
triggers:

```2021/12/11 02:07:31 [error] 28#28: *1 lua entry thread aborted: runtime error: /etc/nginx/crashdown/config/nginx.lua:209: module 'cjson' not found:
	no field package.preload['cjson']
	no file './cjson.lua'
	no file '/usr/local/share/luajit-2.1.0-beta3/cjson.lua'
	no file '/usr/local/share/lua/5.1/cjson.lua'
	no file '/usr/local/share/lua/5.1/cjson/init.lua'
	no file './cjson.so'
	no file '/usr/local/lib/lua/5.1/cjson.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/etc/nginx/crashdown/config/nginx.lua:209: in main chunk, client: 172.17.0.1, ...
```

This is in an `access_by_lua` directive. Thanks!

**Comment by fabiocicerchia** [comment]
I've pushed a new version to the repo, and it's going to be available on docker hub in the next minutes.
Could you please try to use the image `fabiocicerchia/nginx-lua:1-compat` (or any `-compat` tags) and install cjson via luarocks?
