### ISSUE TITLE
AWS ECS setrlimit(RLIMIT_NOFILE, 40000) failed (1: Operation not permitted) error

### ISSUE THREAD

**Issue by eliransu** [fabiocicerchia/nginx-lua#38]
Hi @fabiocicerchia, I'm getting ```2022/02/01 12:51:56 [alert] 27#27: setrlimit(RLIMIT_NOFILE, 40000) failed (1: Operation not permitted)``` error when deploying the Nginx-Lua container to AWS ECS, while locally I managed to run it normally.
could you assist plesae?

Eliran.

**Comment by fabiocicerchia** [comment]
closing the issue for missing information after a few months now.
