### ISSUE TITLE
Why not compile cjson into the image?

### ISSUE THREAD

**Issue by jiangxianliang007** [fabiocicerchia/nginx-lua#55]
**Describe the bug**

fabiocicerchia/nginx-lua:1.21.6-alpine3.15.1-compat
Cannot install cjson
Why not compile cjson into the image?
**To Reproduce**

/ # luarocks install lua-cjson
Installing https://luarocks.org/lua-cjson-2.1.0.10-1.src.rock

lua-cjson 2.1.0.10-1 depends on lua >= 5.1 (5.1-1 provided by VM)
gcc -O2 -fPIC -I/usr/local/include/luajit-2.1 -c lua_cjson.c -o lua_cjson.o
sh: gcc: not found

Error: Build error: Failed compiling object lua_cjson.o

**Expected behavior**

**Screenshots**

**Comment by fabiocicerchia** [comment]
Hi, thank you for opening the issue.
I tried to keep the image as light as possible without adding any luarocks library.
I see there's a missing package gcc, also deliberately not included in order to keep the image light.

**Comment by fabiocicerchia** [comment]
closing the issue as no follow-up happened in the last months. happy to re-open it.
