### ISSUE TITLE
Typo in Nginx configure commands

### ISSUE THREAD

**Issue by adamjakab** [fabiocicerchia/nginx-lua#60]
https://github.com/fabiocicerchia/nginx-lua/blob/acb9ffaab56bf2aeb1e6974c6a229710660f9fdc/nginx/1.21.6/ubuntu/22.04/tpl/Makefile#L35

`$(NGX_CFLAGS)` and `$(NGX_LDOPT)` should be `${NGX_CFLAGS}` and `${NGX_LDOPT}`

The same in line 38

**Comment by fabiocicerchia** [comment]
Thank you @adamjakab for reporting it, do you get some specific errors or is it only for coding consistency?

I double-checked the latest [CI build output](https://app.circleci.com/pipelines/github/fabiocicerchia/nginx-lua/1015/workflows/63c84b04-9975-480e-832f-47b7f30cd925/jobs/6317) and the variables are properly expanded.

**Comment by fabiocicerchia** [comment]
Closing ticket because additional information are missing.
