### ISSUE TITLE
resty-cli support

### ISSUE THREAD

**Issue by AndreMiras** [fabiocicerchia/nginx-lua#63]
**Is your feature request related to a problem? Please describe.**
I'd like to run `busted` tests on my Lua code, but it seems like I would need to run a headless nginx just like https://github.com/openresty/resty-cli

**Describe the solution you'd like**
Provide a resty interpreter or something similar so we can unit test Lua script with access to ngx global scope.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fabiocicerchia** [comment]
@AndreMiras thank you for raising the issue, would you please provide an example of a test you're trying to run on your Lua code?

**Comment by AndreMiras** [comment]
Hi Fabio, thanks for getting back so quickly!
Here's an extract of the type of logic I'm using:
```lua
-- url that do not require api key authorization
local whitelist_urls = {"/whitelisted1/", "/whitelisted2/"}

local function starts_with_one_of(str, tbl)
    for _, value in ipairs(tbl) do
        if string.sub(str, 1, string.len(value)) == value then
            return true
        end
    end
    return false
end

function get_token_list()
    return {"token1", "token2"}
end

function token_in_list(token, token_list)
    for _, v in ipairs(token_list) do
        if v == token then return true end
    end
    return false
end

-- Return a HTTP_UNAUTHORIZED (401) on invalid tokenkey.
local function on_invalid_token()
    ngx.status = ngx.HTTP_UNAUTHORIZED
    ngx.header.content_type = 'application/json'
    ngx.say('{"error": "Invalid token"}')
    ngx.exit(ngx.HTTP_UNAUTHORIZED)
end

local function main()
    local token_list = supabase.get_token_list()
    if starts_with_one_of(ngx.var.uri, whitelist_urls) or token_in_list(ngx.var.http_token, token_list) then
        ngx.say('Hello world!')
    else
        on_invalid_token()
    end
    -- more advanced logic involving lua_shared_dict
    some_more_advanced_logic(token_list, ngx.shared.token_usages)
end

main()
```

The logic is currently relatively trivial, but the complexity will go increasing overtime so I want to make sure all scenarios are properly automated tested without having to setup a complete integration environment.
In this example I've simplified & merged 2 layers together, but in reality code that relies on the `ngx` global is in its own file which should make it easier to unit test.
So the challenge I'm having is dealing with the `ngx` global.
I came across things like [lua-resty-busted](https://luarocks.org/modules/thibaultcha/lua-resty-busted) and I thought it was an interesting approach, but it relies on resty.
Alternatively I could try to mock ngx with busted, but I would lose ngx implementation logic, for instance `ngx.shared.token_usages` is a `lua_shared_dict`.
Some of the scenarios I'd like to test:
- using a whitelisted URL doesn't require a token
- using a token with a non whitelisted URL works
- using an invalid token returns a 401
- some_more_advanced_logic mutate the `ngx.shared.token_usages` dictionary

Later I'll have more logic for instance `get_token_list()` is actually querying a cache and I want it to fail gracefully on error so I want to test error code is always 200 in this case. I also want to introduce some local caching strategy which will increase code complexity so I'd like to test that too.

**Comment by fabiocicerchia** [comment]
I was checking lua-resty-busted and it's quite old (~7 years ago), may be outdated. I managed to install `busted` and try the [default example](https://github.com/thibaultcha/lua-resty-busted#usage).
I'm trying to explore https://github.com/actfint/lua-resty-busted-test and https://github.com/fesily/lua-resty-busted2.

**Comment by AndreMiras** [comment]
Thanks a mil Fabio!
What I'm doing for now is to mock the ngx global, for instance:
```lua
local function ngx_stub()
    return {
        HTTP_UNAUTHORIZED = 401,
        status = nil,
        header = {content_type = nil},
        var = {http_token = "01234", uri = "/"},
        shared = {
            api_keys_usages = {
                get = function() end,
                add = function() end,
                incr = function() end
            },
            api_keys_limits = {get = function() end}
        },
        exit = function() end,
        log = function() end,
        say = function() end,
        timer = {at = function() end}
    }
end

describe("whatever_test", function()
    before_each(function() _G.ngx = mock(ngx_stub()) end)
end)
```

**Comment by fabiocicerchia** [comment]
These are the steps I followed:

```bash
apt install vim git make gcc wget
wget https://raw.githubusercontent.com/openresty/resty-cli/master/bin/resty
chmod +x resty
mv resty /usr/local/bin/
luarocks install moonscript
luarocks install luacov
luarocks install lua-resty-busted
mkdir spec
```

Then I have the following files:

`spec/busted_spec.lua`:  
```lua
-- ref: https://github.com/thibaultcha/lua-resty-busted#usage
describe("lua-resty-busted", function()
  it("should run in ngx_lua context", function()
    assert.truthy(_G.ngx)
    assert.equal(0, ngx.OK)
    assert.equal(200, ngx.HTTP_OK)
  end)
  it("calling ngx.exit should not exit", function()
    -- This test succeeds if busted exits properly since
    -- ngx.exit would prematurely terminate the execution.
    -- Better to run the tests from the Makefile.
    ngx.exit(1)
  end)
end)
```

`spec/resty-runner.lua`:  
```lua
-- ref: https://github.com/lunarmodules/busted/issues/414#issuecomment-792614808
#!/usr/bin/env resty

-- script to run Busted tests using Openresty while setting some extra flags.
--
-- This script should be specified as:
--   busted --lua=<this-file>
--
-- Alternatively specify it in the `.busted` config file


-- These flags are passed to `resty` by default, to allow for more connections
-- and disable the Global variable write-guard. Override it by setting the
-- environment variable `BUSTED_RESTY_FLAGS`.
local RESTY_FLAGS=os.getenv("BUSTED_RESTY_FLAGS") or "-c 4096 -e 'setmetatable(_G, nil)'"

-- rebuild the invoked commandline, while inserting extra resty-flags
local cmd = {
  "exec",
  arg[-1],
  RESTY_FLAGS,
}
for i, param in ipairs(arg) do
  table.insert(cmd, "'" .. param .. "'")
end

local _, _, rc = os.execute(table.concat(cmd, " "))
os.exit(rc)
```
Note: `chmod +x spec/resty-runner.lua` is needed.

`.busted`:  
```lua
return {
  default = {
    lua = "spec/resty-runner.lua",
    verbose = true,
    coverage = false,
    output = "gtest",
  },
}
```

then run the tests:
```
busted spec/
[==========] Running tests from scanned files.
[----------] Global test environment setup.
[----------] Running tests from spec/busted_spec.lua
[ RUN      ] spec/busted_spec.lua @ 2: lua-resty-busted should run in ngx_lua context
[       OK ] spec/busted_spec.lua @ 2: lua-resty-busted should run in ngx_lua context (0.33 ms)
[ RUN      ] spec/busted_spec.lua @ 7: lua-resty-busted calling ngx.exit should not exit
```

I know there's no support for that in my image, but I hope this will help you. I'll think of a proper way to integrate those commands.

**Comment by AndreMiras** [comment]
Awesome, I confirm this is working, thanks a mil!
I ran it with the Alpine base (`fabiocicerchia/nginx-lua:1.23-alpine-compat`) and adapted the instructions slightly.
I'm not using a `.busted` nor the `resty-runner.lua` file, but I'm using `lua-resty-busted` from master which uses `busted-2.0.rc12` and fixes the `attempt to call method 'add_flag' (a nil value)` issue.

This is what I did:
```sh
apk add gcc git make perl vim wget
wget https://raw.githubusercontent.com/openresty/resty-cli/v0.29/bin/resty -O /usr/local/bin/resty
chmod +x /usr/local/bin/resty
# fix the bug: attempt to call method 'add_flag' (a nil value)
luarocks install https://raw.githubusercontent.com/thibaultcha/lua-resty-busted/master/lua-resty-busted-0.0.1-0.rockspec
# using your `spec/busted_spec.lua` example
busted spec/
```

Unfortunately `lua-resty-busted` seems unmaintained, even though it's relatively stable with last fixes from master.
However installing the `resty` as part of the images you provides could still be cool indeed, unless the dependencies (mainly perl I guess) add too much to the image size.
Another option is to make the install optional, but that makes dealing with the docker image more complex.
And last option I'm thinking is to simply document the process as you did and that' would probably be good enough for now

**Comment by fabiocicerchia** [comment]
Thank you very much @AndreMiras, I really appreciate the support! :pray: 

I'm going to add your steps in a dedicated section of the documentation, so at least they are available as a quick snippet to extend the existing image easily.
I'll see whether it is doable to make it customisable via some feature flag, although like you said makes the overall configuration a bit complex to cover all edge cases.

I tried to quickly install it in Alpine and compared the 2 image size:
```
REPOSITORY                 TAG                     IMAGE ID       CREATED         SIZE
<none>                     <none>                  3d6c4b50b9bb   3 seconds ago   109MB
fabiocicerchia/nginx-lua   alpine                  447986abf723   9 days ago      71.6MB
```
resulting in an increase of 50% (a little over 30MB).

I'm going to run this benchmark with other distro and gather details on the impact of it.

**Comment by AndreMiras** [comment]
Thanks for taking a look.
30MB more is totally not worth it, we all like slim images.
I imagine we could cut that with multistage builds since we don't need gcc, git, make, vim and wget at runtime, but I don't think it's worth making the image building process more complex still.
I think having it documented is more than enough and we can base our image of this to add whatever we need.

**Comment by fabiocicerchia** [comment]
Actually, the 50% increase was only for adding `perl`. I didn't even consider adding `gcc` and `make`. :innocent: 

```
REPOSITORY                 TAG                     IMAGE ID       CREATED          SIZE
fabiocicerchia/nginx-lua   all-deps                f65a58d42668   2 seconds ago    278MB
fabiocicerchia/nginx-lua   only-perl               66a2e2b4ecb8   30 seconds ago   109MB
<none>                     <none>                  3d6c4b50b9bb   2 hours ago      109MB
fabiocicerchia/nginx-lua   alpine                  447986abf723   9 days ago       71.6MB
```
