### ISSUE TITLE
能否不开启linux临时缓存区，我们线上环境遇到了下载大文件时会在1GB左右报错，查询资料后应该是开始了默认缓存区大小的原因，我们需要手动更改configmap才可以修复，可能其他人也会遇到类似问题，建议修改

### ISSUE THREAD

**Issue by Creat-qc** [fabiocicerchia/nginx-lua#67]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fabiocicerchia** [comment]
> Is it possible not to open the linux temporary cache area? In our online environment, when downloading large files, an error will be reported at about 1GB. After querying the data, it should be the reason for the default cache area size. We need to manually change the configmap to fix it, and it may be other  People will encounter similar problems, it is recommended to modify

Is o

**Comment by Creat-qc** [comment]
i only set proxy_max_temp_file_size 0;  in configmap, now i am doing a new lua-nginx 😂,and i found different version about nginx is strange, first i use 1.25.0,but that aleady use pcre2, even i install pcre2 and devel, still wrong, so i want try 1.20 (nginx), it ask me edit a var "cookie" to "cookies", but it ask me to do the opposite in 1.25.0

**Comment by fabiocicerchia** [comment]
@Creat-qc I was trying out your nginx config, and it seemed to work ok. I was using `fabiocicerchia/nginx-lua:alpine`. Older versions are not supported, so please use 1.25.
Also in the config map, I don't see the property you've mentioned `proxy_max_temp_file_size`.
