### ISSUE TITLE
lua-resty-limit-traffic support

### ISSUE THREAD

**Issue by xivanc** [fabiocicerchia/nginx-lua#77]
**Is your feature request related to a problem? Please describe.**
In my projects I need more detailed control over rate limiting, which default NGINX does not support

**Describe the solution you'd like**
Install a lua-resty-limit-traffic library (https://github.com/openresty/lua-resty-limit-traffic) in this docker image

**Comment by fabiocicerchia** [comment]
the functionality has been released
